### ISSUE TITLE
Test upstream update b2594b8..81e7a5b (2020-06-06)

### ISSUE THREAD

**Issue by nobiot** [nobiot/md-roam#20]
I can observe some changes around the treatment of #+ROAM_xx properties (such as #+ROAM_ALIAS), and related functions. 

Examples:

- [x] [(feat): make roam properties case-insensitive (#757) ](https://github.com/org-roam/org-roam/commit/0cd4bc05c5d129531ff7f4cb1e40cdc3487215ad)
- [x] [(fix): simplify org-roam--str-to-list (#762)](https://github.com/org-roam/org-roam/commit/c61f7e20f266627743412c6c458ec70dce350bd0)

This might be also an interesting one to test (I have never had a problem, but it might be good to see if something like `roam_alias`: "malformed value` (note the missing closing `"`) causes an error in db cache build.

- [x] [(fix): fix bad behaviour on malformed properties (#763)](https://github.com/org-roam/org-roam/commit/0cd4bc05c5d129531ff7f4cb1e40cdc3487215ad)

In addition, this should not affect me as I explicitly define `elisp` for the variable. Windows might be more susceptible if any influence at all.
- [(fix): fix org-roam--list-files elisp fallback (#764) ](https://github.com/org-roam/org-roam/commit/81e7a5b23101887a60516f4a7645863ed327e8d5)
No testing for me to do; I'll stick with explicitly setting `elisp` (or `rg`, which I have confirmed to work, but [will be more performant only after 2500-3000 files, at least on Window](https://org-roam.discourse.group/t/what-does-it-feel-like-to-work-with-10-000-notes-in-org-roam-benchmarking-org-roams-search-methods/227)s)

**Comment by nobiot** [comment]
org-roam#757 seems to work together with Md-roam
![image](https://user-images.githubusercontent.com/12507865/83946529-b3a3fa80-a811-11ea-8884-fad0ca98456c.png)

**Comment by nobiot** [comment]
(fix): fix bad behaviour on malformed properties (#763) seems to work.
If I understand the fix correctly, this is what the intended behaviour is. 
I do not adapt `org-roam-doctor` so far, so that's not relevant (for the moment).

![image](https://user-images.githubusercontent.com/12507865/83946589-19908200-a812-11ea-8a8c-776139636891.png)

**Comment by nobiot** [comment]
(fix): simplify org-roam--str-to-list (#762)

org-roam--str-to-list is used in
- org-roam--extract-titles-alias (to extract aliases from a note)
- org-roam--extract-tags-prop (to extract tags from a note)

Md-roam currently does not explicitly support tags.

Aliases work.

![image](https://user-images.githubusercontent.com/12507865/83946892-e8b14c80-a813-11ea-891d-d054c137744f.png)
