### ISSUE TITLE
(fix) Catch up to upstream commit 265182a

### ISSUE THREAD

**Issue by nobiot** [nobiot/md-roam#9]
A good amount of cahnges have been introduced, as follows. Some of them may be already incorporated in md-roam. It's a good check list. I'll see which ones can be supported. 

https://github.com/org-roam/org-roam/blob/master/CHANGELOG.md
Breaking Changes

- ~~#523 remove org-roam-completion-fuzzy-match in favor of using completion mechanism's configuration options directly~~ [not relevant]]
- ~~#547 Deprecate org-roam-db--maybe-update, in favour of org-roam-db--update-maybe.~~ [not relevant]
- [X] #547 Added type column to the refs table. [#10 ]

Features

- [X] #538 Optionally use text in first headline as title [#15 ]
- ~~#553 Add prefix argument to org-roam-db-build-cache for forcing rebuilds~~ (not relevant)
- [X] #560 Apply 'error face to distinguish broken links [markdown-wiki-link-fontify-missing]
- ~~#570 Add org-roam-doctor to diagnose org-roam files~~ [not relevant]

**Comment by nobiot** [comment]
#10 can be used with upstream commit 265182a. However, I want to be a bit more systematic about testing it, and check these changes. I'll keep this issue for now.

**Comment by nobiot** [comment]
#538 Optionally use text in first headline as title
Added support via #14 (issue #15 )

**Comment by nobiot** [comment]
For #560 Apply 'error face to distinguish broken links, I should be able rely on `markdown-mode` variable, `markdown-wiki-link-fontify-missing`.  If non-nil, it should apply `markdown-missing-link-face`. The variable is nil by default for performance.
